### ISSUE TITLE
Tooltip visible after removing source element

### ISSUE THREAD

**Issue by woellie123** [basmilius/latte-ui#36]
When a tooltip is present on a element and you remove that element, the tooltip will still be visible (see attached video).
![tooltip_error](https://user-images.githubusercontent.com/6154428/59568176-7b8f2f00-9077-11e9-830e-9fec683f654f.gif)

**Comment by basmilius** [comment]
Proposed fix for [packages/latte-ui/src/vue/component/Uploader.vue](https://github.com/basmilius/latte-ui/blob/master/packages/latte-ui/src/vue/component/Uploader.vue):

Call `latte:tooltip:hide` action in `removeFile`.
