### ISSUE TITLE
No icons

### ISSUE THREAD

**Issue by Julianvschijndel** [basmilius/latte-ui#45]
Hey,

I cannot see the icons. How can I fix this?

Screen: https://prnt.sc/od2jvc

Website code: https://pastebin.com/pYQdCbYf

Hope you can tell me how to solve/fix.

**Comment by basmilius** [comment]
This is not relevant to this project, but you should add the Material Design Icons library to your own project. Just add this as a stylesheet to your code:

`https://cdn.materialdesignicons.com/3.7.95/css/materialdesignicons.min.css`

**Comment by Julianvschijndel** [comment]
I'm sorry, I didn't know that, I tought it was included with the CSS i'm sorry.
