### ISSUE TITLE
Intranet Darkmode

### ISSUE THREAD

**Issue by WouterSchotman** [basmilius/latte-ui#52]
Bij het toevoegen van nieuwe inloggegevens in de darkmode van het intranet, heeft de tekst in  'Relatie' nog zwarte/donkere tekst.

![Darkmode-bugje](https://user-images.githubusercontent.com/53252455/64853579-f25aaa80-d61b-11e9-874b-81d2d734e061.jpg)

**Comment by basmilius** [comment]
Fixed in IdeeMedia/intranet@ee30751a06f96a8257e3af768ba88d0dcfc3f231
