### ISSUE TITLE
An update for this project.

### ISSUE THREAD

**Issue by basmilius** [basmilius/latte-ui#60]
Hi! So, there weren't any updates in the past couple of months to this project and that is with a good reason. As you probably know, Vue 3 is in RC right now and I've been working on a 2.x version of Latte UI, build for Vue 3.

When it's ready for alpha, I'll publish the fresh code in this repository.

Thnx for the patience! 😃

**Comment by BasToTheMax** [comment]
Oke

**Comment by BasToTheMax** [comment]
Ik ben benieuwd
